package main

import (
	"flag"
	"fmt"
	"github.com/ericaro/mrepo"
	"os"
)

var (
	makefile = flag.Bool("makefile", false, "Print dependencies in a Makefile format")
	help     = flag.Bool("h", false, "Print this help.")
)

func main() {
	flag.Parse()
	if *help {
		fmt.Println(`USAGE git deps [-options]
			
DESCRIPTION:

  Manage git dependencies.
  Scan recursively the current directory, looking for embedded git repositories.
  By default, it just prints out each one in a tabular way.

  You can print them in a Makefile format (-makefile)


OPTIONS:
`)
		flag.PrintDefaults()

		fmt.Println(`
EXAMPLES:

git deps

git deps -makefile > Makefile
`)
		os.Exit(-1)
	}

	// use wd by default
	wd, err := os.Getwd()
	if err != nil {
		fmt.Printf("Error, cannot determine the current directory. %s\n", err.Error())
	}
	//scan for current wd
	scanner := mrepo.NewScan(wd)
	go func() {

		err = scanner.Find()
		if err != nil {
			fmt.Printf("Error scanning current directory (%s). %s", wd, err.Error())
		}
	}()

	//get the repository chan generated by Find call.
	repositories := scanner.Repositories()
	//select the "Depender" i.e what to do with each repo
	var d mrepo.Depender
	switch {
	case *makefile:
		d = mrepo.Makedeps
	default:
		d = mrepo.Deps
	}
	mrepo.Dependencies(repositories, wd, d)
}
